<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Vendor;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Toko Langgeng
            ['name' => 'Abon Sapi', 'description' => 'Daun Mas', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Agar - Agar', 'description' => 'Swallow Globe Plain', 'unit' => 'Dos @12pack', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Agar - Agar', 'description' => 'Nutrijel Plain', 'unit' => 'Dos @12pack', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Beras Ketan Hitam', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Beras Ketan Putih', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Beras Premium', 'description' => 'Platinum', 'unit' => 'Karung @5kg', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Beras Medium', 'description' => null, 'unit' => 'Karung @5kg', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Bihun Super', 'description' => 'Tanam Jagung @320gr', 'unit' => 'Pack @960gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Bumbu Pecel', 'description' => 'Sinti', 'unit' => 'Pcs @200gr', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Coklat Bubuk', 'description' => 'Parrot', 'unit' => 'Pcs @100gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Gula Merah/Kelapa', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Gula', 'description' => 'Gulaku Kuning', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Kacang Hijau', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Kacang Tanah', 'description' => 'Kupas (ada kulit ari)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Kecap Manis', 'description' => 'ABC', 'unit' => 'Bottle @600ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Kopi 2', 'description' => 'Kapal Api Silver', 'unit' => 'Pack @350gr', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Margarin', 'description' => 'Forvita, Blue Band @200gr', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Mie Instant Goreng', 'description' => 'Indomie', 'unit' => 'Dos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Mie Instant Kuah', 'description' => 'Indomie Ayam Bawang', 'unit' => 'Dos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Mie Telur', 'description' => '3 Ayam', 'unit' => 'Pcs @200gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Minyak Goreng', 'description' => 'Rose Brand', 'unit' => 'Galon @5 Ltr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Minyak Wijen', 'description' => 'Oh Guan Hing', 'unit' => 'Bottle @195ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Mutiara', 'description' => null, 'unit' => 'Pack @250gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Ragi Instan', 'description' => 'Fermipan', 'unit' => 'Pack @44gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Santan Kelapa', 'description' => 'Kara Sun', 'unit' => 'Pcs @200ml', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Saos Sambal', 'description' => 'Delmonte', 'unit' => 'Bottle @335ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Sirup', 'description' => 'Marjan Cocopandan', 'unit' => 'Bottle @460ml', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Susu Kental Manis Putih', 'description' => 'Frisian Flag', 'unit' => 'Can @370gr', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Telur Asin', 'description' => null, 'unit' => 'Biji/Pc', 'price' => 10000, 'category' => 'Telur', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Telur Ayam Horn', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Telur', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Telur Bebek', 'description' => null, 'unit' => 'Biji/Pc', 'price' => 10000, 'category' => 'Telur', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Tepung Bumbu Crispy', 'description' => 'Sajiku, Sasa, Kobe', 'unit' => 'Pcs @900gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Tepung Panir', 'description' => 'Le Chef @500gr', 'unit' => 'Pcs @1kg', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Tepung Terigu', 'description' => 'Segitiga Biru', 'unit' => 'Pcs @1kg', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Vanili', 'description' => 'Koepoe - Koepoe', 'unit' => 'Pack @6pcs', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Slai Coklat', 'description' => 'Chocolate Peanut', 'unit' => 'Can @300gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Krupuk Puli', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Slai Srikaya', 'description' => 'Morin Kaya', 'unit' => 'Can @330gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Susu UHT Coklat', 'description' => 'Indomilk, Frisian Flag, Diamond', 'unit' => 'Pcs @950ml', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Susu UHT Putih', 'description' => 'Frisian Flag', 'unit' => 'Pcs @950ml', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Bumbu Gulai', 'description' => 'Indofood', 'unit' => 'Pcs @35gr', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Bumbu Rawon', 'description' => 'Indofood', 'unit' => 'Pcs @54gr', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Bumbu Soto', 'description' => 'Indofood', 'unit' => 'Pcs @40gr', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Garam', 'description' => 'Refina 4 x @500gr', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Ketumbar Bubuk', 'description' => 'Koepoe-Koepoe', 'unit' => 'Bottle @25gr', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Kunyit Bubuk', 'description' => 'Koepoe-Koepoe', 'unit' => 'Bottle @25gr', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Merica Bubuk', 'description' => 'Koepoe-Koepoe', 'unit' => 'Bottle @85gr', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Bakso Sapi Premium', 'description' => null, 'unit' => 'Pack @50pc', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Bakso Sapi Medium', 'description' => null, 'unit' => 'Pack @50pc', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Sosis / Beef Sausage', 'description' => 'Champ', 'unit' => 'Pack @1kg', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Sosis Sapi Horeca Ss', 'description' => 'Champ', 'unit' => 'Pack @1kg', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Arang', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Lain-lain', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Tusuk Sate', 'description' => null, 'unit' => 'Pak @100 Pcs', 'price' => 10000, 'category' => 'Lain-lain', 'vendor' => 'Toko Langgeng'],
            ['name' => 'Kering Tempe Kentang', 'description' => null, 'unit' => '@250gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Toko Langgeng'],

            // Tip Top
            ['name' => 'Bumbu Masak / Vitsin', 'description' => 'Ajinomoto', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Cuka/Vinegar', 'description' => 'Dua Belibis', 'unit' => 'Bottle @650ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Kaldu Sapi Atau Ayam', 'description' => 'Royco', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Kecap Asin', 'description' => 'ABC', 'unit' => 'Bottle @620ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Kecap Raja Rasa', 'description' => null, 'unit' => 'Bottle @600ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Kopi 1', 'description' => 'Kapal Api Special', 'unit' => 'Pack @350gr', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Tip Top'],
            ['name' => 'Saos Inggris', 'description' => 'ABC', 'unit' => 'Bottle @195ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Saos Teriyaki-Teriyaki Sauce', 'description' => 'Saori', 'unit' => 'Bottle @275ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Saos Tiram', 'description' => 'Saori', 'unit' => 'Bottle @270ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Saos Tomat/Tomato Ketchup', 'description' => 'ABC, Delmonte', 'unit' => 'Bottle @335ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Sarden Tuna', 'description' => 'ABC', 'unit' => 'Can @425gr', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Tip Top'],
            ['name' => 'Susu Coklat Bubuk', 'description' => 'Indomilk, Frisian Flag, Milo', 'unit' => 'Pack @400gr', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Tip Top'],
            ['name' => 'Susu Kental Manis Coklat', 'description' => 'Indomilk, Frisian Flag', 'unit' => 'Can @370gr', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Tip Top'],
            ['name' => 'Susu Putih Bubuk', 'description' => 'Indomilk, Frisian Flag', 'unit' => 'Pack @400gr', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Tip Top'],
            ['name' => 'Tauco Merah', 'description' => 'Kokita', 'unit' => 'Bottle @400ml', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Teh Seduh', 'description' => 'Tong Tji, Cap Botol, Teh Poci', 'unit' => 'Pack @6pcs', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Tip Top'],
            ['name' => 'Teh/Tea Celup', 'description' => 'Sariwangi, Tong Tji, Teh Poci', 'unit' => 'Pack @25sht', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Tip Top'],
            ['name' => 'Tepung Beras', 'description' => 'Rose Brand Putih @500gr', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Tip Top'],
            ['name' => 'Tepung Jagung', 'description' => 'Maizenaku', 'unit' => 'Pcs @300gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Tip Top'],
            ['name' => 'Slai Stroberry', 'description' => 'Morin Strawberry', 'unit' => 'Can @330gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Tip Top'],
            ['name' => 'Susu Bubuk', 'description' => 'Max Creamer', 'unit' => 'Bottle @200gr', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Tip Top'],
            ['name' => 'Corned Beef', 'description' => 'Pronas', 'unit' => 'Can @340gr', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Tip Top'],
            ['name' => 'Tepung Tapioka', 'description' => 'Gunung Agung', 'unit' => 'Pcs @500gr', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Tip Top'],
            ['name' => 'Terasi Bonang', 'description' => 'ABC', 'unit' => 'Pack @20sht', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Tip Top'],
            ['name' => 'Wong Coco', 'description' => 'Kara', 'unit' => 'Pack @1kg', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Tip Top'],

            // Sentra Ikan Laut
            ['name' => 'Ikan Asin Jambal', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Ikan Teri', 'description' => 'Teri Jengki', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Babat', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Bebek', 'description' => '1,2 Kg/Ekor (Frozen)', 'unit' => 'Ekor/Pcs', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Buntut Sapi/Potong', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Daging Giling', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Daging Kambing', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Daging Rawonan/Soto', 'description' => 'Shankel (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Daging Satean', 'description' => 'Blade (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Daging Utk Rendang,Empal', 'description' => 'Knuckel (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Iga Sapi / Potong', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Kikil Cut', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Lidah', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Paru', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Lulur Luar', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Lulur Dalam', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Ayam Dada Fillet', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Ayam Paha Fillet', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Daging Iris Tipis', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Bandeng', 'description' => '6 - 7 Ekor/Kg (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Gurami', 'description' => '1 - 2 Ekor/Kg (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Kembung', 'description' => '6 - 7 Ekor/Kg (Bentrong Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Kepiting/Rajungan', 'description' => '2 Ekor/Kg (Fresh)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Patin', 'description' => '2 - 3 Ekor/Kg (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Tengiri', 'description' => '1 - 3 Kg/Ekor (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Tongkol / Tuna', 'description' => 'Tuna 1 - 1,1 Kg/Ekor (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Udang Nasi Goreng', 'description' => 'Vaname 40 - 50 (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Fillet Kakap', 'description' => 'Frozen', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],
            ['name' => 'Ikan Panggangan', 'description' => 'Cakalang / Tuna (Dried)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Sentra Ikan Laut'],

            // Pasar
            ['name' => 'Ikan Jombrang', 'description' => null, 'unit' => 'Pack @100gr', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Asem Jawa', 'description' => '3 x @400gr', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Pasar'],
            ['name' => 'Bawang Merah', 'description' => 'Super', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Pasar'],
            ['name' => 'Belimbing Wuluh', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Pasar'],
            ['name' => 'Jeruk Nipis / Jeruk Pecel', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Pasar'],
            ['name' => 'Kayu Manis', 'description' => null, 'unit' => '@100gr (Ons)', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Pasar'],
            ['name' => 'Bayam/Spinach', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Kacang Panjang', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Kelapa Utuh', 'description' => 'Kelapa Tua Batok', 'unit' => 'Biji/Pc', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Kemangi', 'description' => null, 'unit' => 'Ikat', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Kenikir', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Mentimun', 'description' => 'Timun Sp', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Petai Kupas', 'description' => 'Petai Papan', 'unit' => 'Per Lembar', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Sawi Hijau', 'description' => 'Caesim', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Tahu', 'description' => null, 'unit' => 'Pack @10pcs', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Tauge Besar', 'description' => 'Tauge', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Tempe', 'description' => 'Bungkus Daun Pisang', 'unit' => 'Pcs', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Pasar'],
            ['name' => 'Alpokat', 'description' => 'KEMATANGAN 50%', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Apel Manalagi', 'description' => 'Musiman', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Apel Merah', 'description' => 'Fuji', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Biji Dawet', 'description' => 'Cendol', 'unit' => '@500gr', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Cincau', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Jeruk/Orange', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Melon', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Pear', 'description' => 'KEMATANGAN 50%', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Pepaya/Papaya', 'description' => 'KEMATANGAN 50%', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Pisang Kepok', 'description' => 'KEMATANGAN 50%', 'unit' => 'Sisir', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Semangka (Tanpa Biji)', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Mangga', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Salak', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Anggur', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Buah Naga', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Pasar'],
            ['name' => 'Ayam Horn', 'description' => '1,3 Kg/Ekor (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Pasar'],
            ['name' => 'Ayam Kampung', 'description' => '900 - 1000 Gr/Ekor (Frozen)', 'unit' => 'Ekor/Pc', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Pasar'],
            ['name' => 'Ayam Merah', 'description' => null, 'unit' => 'Ekor', 'price' => 10000, 'category' => 'Daging & Unggas', 'vendor' => 'Pasar'],
            ['name' => 'Bawal Hitam', 'description' => '600 - 800 Gr/Ekor (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Cumi Utuh', 'description' => '5 - 7 Cm/Ekor (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Kakap Skin On', 'description' => '600 - 1 Kg/Ekor (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Lele', 'description' => 'Ukuran Sedang (Fresh)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Mujair/Nila', 'description' => '6 - 7 Ekor/Kg (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Pindang Marning', 'description' => '2 - 3 Pcs/Pack (Dried)', 'unit' => 'Kotak/Box', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Pindang Salem', 'description' => '2 - 3 Pcs/Pack (Dried)', 'unit' => 'Kotak/Box', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Pindang Tongkol', 'description' => 'Tanpa Tulang & Kepala', 'unit' => 'Kotak/Box', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],
            ['name' => 'Udang', 'description' => 'Vaname 50 - 60 (Frozen)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Ikan & Seafood', 'vendor' => 'Pasar'],

            // Paskomnas
            ['name' => 'Krupuk Udang', 'description' => 'Kecil', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Paskomnas'],
            ['name' => 'Kulit Lumpia', 'description' => null, 'unit' => 'Pack @40pcs', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Paskomnas'],
            ['name' => 'Kulit Martabak', 'description' => null, 'unit' => 'Pack @40pcs', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Paskomnas'],
            ['name' => 'Kulit Pangsit Tipis', 'description' => null, 'unit' => 'Pack @40pcs', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Paskomnas'],
            ['name' => 'Bawang Bombay', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Bawang Putih', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Cengkeh', 'description' => null, 'unit' => '@100gr (Ons)', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Jeruk', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Salam', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Sereh', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Jahe Utuh', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Jeruk Purut / Limo', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Jintan', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Kemiri', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Kencur', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Ketumbar', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Kluwek', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Kunyit', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Laos', 'description' => 'Lengkuas', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Merica Utuh', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Pala', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Temu Kunci', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Bumbu', 'vendor' => 'Paskomnas'],
            ['name' => 'Bawang Pre', 'description' => 'Daun Bawang Besar', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Brokoli', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Buncis', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Cabe Hijau Besar', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Cabe Hijau Kecil', 'description' => 'Rawit Hijau', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Cabe Merah Besar', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Cabe Merah Kecil', 'description' => 'Rawit Merah', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Bawang', 'description' => 'Daun Bawang Kecil', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Belinjo/ So', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Pandan', 'description' => null, 'unit' => 'Ikat', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Pepaya Muda', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Daun Pisang Utk Bungkus', 'description' => null, 'unit' => 'Ikat', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Gambas', 'description' => 'Oyong', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Jagung Kulit Utuh', 'description' => 'Jagung Manis Kulit', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Jagung Muda / Janten', 'description' => 'Jagung Muda Kulit / Putren', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Kacang Tanah Utuh', 'description' => 'Kacang Tanah Kulit', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Kangkung', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Kembang Kol', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Kembang Turi', 'description' => 'Tidak Tersedia di Jakarta', 'unit' => 'Kg/Kilos', 'price' => 0, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Kentang', 'description' => 'Sedang (Ab)', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Krai', 'description' => 'Tidak Tersedia di Jakarta', 'unit' => 'Kg/Kilos', 'price' => 0, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Kubis', 'description' => 'Kol', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Labu Putih', 'description' => 'Labu Air', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Manisah/Labu Siam', 'description' => 'Labu Siam', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Melinjo Biji', 'description' => 'Buah Melinjo', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Nangka Muda', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Pare', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Sawi Daging', 'description' => 'Pakcoy', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Sawi Asin', 'description' => null, 'unit' => 'Pack @350gr', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Sawi Putih', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Seledri', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Slada', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Tauge Kecil/Pendek', 'description' => 'Tauge Rawon', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Terong Panjang Ungu/Hijau', 'description' => 'Ungu', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Tomat/Tomato', 'description' => 'Merah', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Wortel - Lokal', 'description' => 'Super', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Labu Kuning', 'description' => 'Labu Parang', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Jamur Champignon', 'description' => null, 'unit' => 'Pack @250gr', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Cabe Merah Keriting', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Sayuran', 'vendor' => 'Paskomnas'],
            ['name' => 'Belewa', 'description' => 'Musiman', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],
            ['name' => 'Kolang-Kaling', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],
            ['name' => 'Nenas', 'description' => 'KEMATANGAN 50%', 'unit' => 'Biji/Pc', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],
            ['name' => 'Pisang Ambon', 'description' => 'KEMATANGAN 50%', 'unit' => 'Sisir', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],
            ['name' => 'Pisang Cavendis', 'description' => 'STEP 2', 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],
            ['name' => 'Pisang Raja', 'description' => 'KEMATANGAN 50%', 'unit' => 'Sisir', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],
            ['name' => 'Singkong / Ketela Pohon', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],
            ['name' => 'Ubi Jalar', 'description' => null, 'unit' => 'Kg/Kilos', 'price' => 10000, 'category' => 'Buah-buahan', 'vendor' => 'Paskomnas'],

            // Sari Roti
            ['name' => 'Roti Tawar', 'description' => 'Sari Roti Original 3 + Pandan 2', 'unit' => 'Pack', 'price' => 10000, 'category' => 'Bahan Kering', 'vendor' => 'Sari Roti'],

            // Toko Ronny
            ['name' => 'Aqua Galon + Isi', 'description' => 'Aqua / Le Minerale', 'unit' => 'Galon', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Ronny'],
            ['name' => 'Aqua Isi ulang', 'description' => 'Aqua / Le Minerale', 'unit' => 'Galon', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Ronny'],
            ['name' => 'Air Minum Botol @600ml', 'description' => 'Aqua / Le Minerale', 'unit' => 'Dus', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Ronny'],
            ['name' => 'Air Minum Botol @1500ml', 'description' => 'Aqua / Le Minerale', 'unit' => 'Dus', 'price' => 10000, 'category' => 'Minuman', 'vendor' => 'Toko Ronny'],
        ];

        $vendorCache = [];

        foreach ($products as $data) {
            $vendorName = $data['vendor'];

            if (!isset($vendorCache[$vendorName])) {
                $vendorCache[$vendorName] = Vendor::where('name', $vendorName)->value('id');
            }

            Product::create([
                'vendor_id'   => $vendorCache[$vendorName],
                'name'        => $data['name'],
                'description' => $data['description'],
                'unit'        => $data['unit'],
                'harga_jual'  => $data['price'],
                'category'    => $data['category'],
                'is_active'   => true,
            ]);
        }
    }
}
